project_name: DefaultProject
memory_ledger_path: memory_ledger.json
audit:
  max_total_blocks: 100
  max_block_age_days: 30
collapse:
  enabled: true
  strategy: archive
  thresholds:
    max_total_blocks: 80
    max_age_days: 20
  selection:
    priority: oldest_creation
    keep_min_blocks: 5
memory_blocks:
  required_tags:
  - core_goal
snapshots:
  snapshot_directory: .statelock_snapshots/
  include_patterns:
  - '*.log'
  - agent_outputs/
  exclude_patterns:
  - .venv/
  - __pycache__/
  - '*.pyc'
  - .git/
  - .neuronbox_snapshots/
